import { Toaster } from '@/components/ui/sonner';

import './globals.css';

import { ClerkProvider } from '@clerk/nextjs';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Morent - Car rental',
    template: '%s',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className='!w-full'>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
